export const NEWSLETTER = {
  eyebrow: "Carta da comunidade GDG",
  titleBefore: "GDG Jobs ",
  titleEm: "Letter",
  lead: "Vagas curadas, encontros e aprendizados da comunidade GDG Lauro de Freitas — uma carta objetiva, sem spam.",
  subscribeTitle: "Inscrever-se",
  subscribeLead: "Deixe seu nome e e-mail para receber as próximas edições. A captura real chega na Sprint 7.",
  nameLabel: "Nome",
  namePlaceholder: "Seu nome",
  emailLabel: "E-mail",
  emailPlaceholder: "voce@email.com",
  subscribeCta: "Em breve",
  subscribeNote: "Integração na Sprint 7 (C-05).",
  issuesTitle: "Edições recentes",
  issuesLead: "Prévia estática para homologação — as edições ainda não abrem.",
  issueCta: "Ler edição",
  issues: [
    {
      id: "ed-04",
      title: "DevFest, vagas curadas e o que a comunidade construiu em setembro",
      date: "Há 1 semana",
      excerpt: "Como acompanhar o DevFest Lauro 2026, o que mudou no catálogo de vagas e um recorte das conversas da comunidade.",
    },
    {
      id: "ed-03",
      title: "Matching com clareza: o que o GDG Jobs mostra (e o que ainda não)",
      date: "Há 3 semanas",
      excerpt: "Critérios visíveis, curadoria humana e o caminho até um fluxo de candidatura com um clique.",
    },
    {
      id: "ed-02",
      title: "Do meetup ao portfólio: três formas de crescer com o GDG Lauro",
      date: "Há 1 mês",
      excerpt: "Encontros, contribuição em projetos da comunidade e vagas alinhadas ao que você já pratica.",
    },
    {
      id: "ed-01",
      title: "Bem-vindo à GDG Jobs Letter",
      date: "Há 2 meses",
      excerpt: "Por que uma carta da comunidade, o que você vai receber e como vamos evitar ruído na caixa de entrada.",
    },
  ],
  ctaEyebrow: "Comunidade GDG",
  ctaTitle: "Seu próximo desafio pode",
  ctaTitleBreak: "estar a um clique.",
  ctaLead: "Crie seu perfil no GDG Jobs enquanto a letter abre inscrições.",
  ctaAction: "Criar perfil gratuito",
};
